#!/bin/bash

set -e

# install mimetypes
if type xdg-mime > /dev/null; then
	xdg-mime install /opt/l5rcm/mime/mime-file-l5r.xml 
	xdg-mime install /opt/l5rcm/mime/mime-file-l5rcmpack.xml
fi

# install icon resources
if type xdg-icon-resource > /dev/null; then
	xdg-icon-resource install --novendor --context mimetypes --size 64 /usr/share/pixmaps/l5rcm.png x-l5r-character
	xdg-icon-resource install --novendor --context mimetypes --size 128 /usr/share/pixmaps/l5rcmpack.png x-l5r-pack
fi	

# install .desktop file
if type xdg-desktop-menu > /dev/null; then
	xdg-desktop-menu install --novendor /usr/share/applications/l5rcm.desktop
fi	

# compile python files
python -m compileall -f /opt/l5rcm/
