#!/bin/bash

set -e

# install mimetypes
xdg-mime install /opt/l5rcm/mime/mime-file-l5r.xml 
xdg-mime install /opt/l5rcm/mime/mime-file-l5rcmpack.xml
xdg-icon-resource install --novendor --context mimetypes --size 64 /usr/share/pixmaps/l5rcm.png x-l5r-character
xdg-icon-resource install --novendor --context mimetypes --size 128 /usr/share/pixmaps/l5rcmpack.png x-l5r-pack

# install .desktop file
xdg-desktop-menu install --novendor /usr/share/applications/l5rcm.desktop

# compile python files
python -m compileall -f /opt/l5rcm/
