#!/bin/bash

set -e

# remove mimetypes
xdg-mime uninstall /opt/l5rcm/mime/mime-file-l5r.xml 
xdg-mime uninstall /opt/l5rcm/mime/mime-file-l5rcmpack.xml
xdg-icon-resource uninstall --novendor --context mimetypes --size 64 /usr/share/pixmaps/l5rcm.png x-l5r-character
xdg-icon-resource uninstall --novendor --context mimetypes --size 128 /usr/share/pixmaps/l5rcmpack.png x-l5r-pack

# uninstall .desktop file
xdg-desktop-menu uninstall --novendor /usr/share/applications/l5rcm.desktop

# delete pyc
find /opt/l5rcm/ | grep .pyc | xargs rm
